---
sudo: required

services:
- docker

language: python

python:
- 3.5

install:
- touch .coverage
- ls -l .coverage
- pip install codecov
- make init-venv
- make build-travis
# give time to the DB to be ready
- sleep 2
- make init-db

script:
- docker-compose -f docker-compose-dev.yml exec web make test-travis
- ls -l .coverage
- codecov

matrix:
  fast_finish: true
